### ISSUE TITLE
Nominas no funcionan correctamente

### ISSUE THREAD

**Issue by Lumexio** [Comet-Pocket-Machinery/Pocket-Bar#16]
Se supone que el metodo nominasToPay() en el controlador NominasController en la ruta api/nominas/pay
funcione con el request siguiente, pero reporta problemas al enviarlo con codigo 500
```json
{
 "payroll": [
  {
   "id": 1,
   "name": "Leonora Considine",
   "name_rol": "Gerencia",
   "nominas": 827.39
  },
  {
   "id": 2,
   "name": "Jace Kirlin",
   "name_rol": "Gerencia",
   "nominas": 237.21
  },
 ],
 "total_nominas": 3915.1800000000003
}
```

**Comment by Lumexio** [comment]
Error al enviar data:

```json
{
"message": "SQLSTATE[42S22]: Column not found: 1054 Unknown column 'amount' in 'field list' (SQL: select sum(`amount`) as aggregate from `cash_register_close_data_tbl` where `workshift_id` = 1)",
"exception": "Illuminate\\Database\\QueryException",
"file": "/Users/fsm/Projects/web-personal/Pocket-Bar/pocket-bar-api/vendor/laravel/framework/src/Illuminate/Database/Connection.php",
"line": 712,
}
```

**Comment by NathanRomero** [comment]
Ya quedo

**Comment by Lumexio** [comment]
El metodo no estaba funcionando puesto que no fue **probado** antes de subirse, el error radicaba en la falta del atributo timestamps en las migraciones y unos detalles en el formato definido en el controlador.
El atributo de propina lo elimine puesto que no tiene uso en esa tabla de nominas, puesto que en la correción anterior solo fue seteado a 0 sin ser eliminado por completo.
El nombre del objeto Id estaba mal escrito.
Ya esta funcional el metodo nominas.
