### ISSUE TITLE
Reporte de total de venta y propinas por mesero y barra

### ISSUE THREAD

**Issue by Lumexio** [Comet-Pocket-Machinery/Pocket-Bar#24]
Esto es parte del metodo workshift que muestra los resultados de de ventas y gastos de la noche

**Comment by Lumexio** [comment]
`json
{
 "workshift_report": [
  {
   "user_id": 1,
   "nombre_employee": "pepe",
   "rol": "Bartender",
   "total_workshift_sales": "12000",
   "tips": "200",
   "closed_tickets": [
    {
     "id": 4,
     "status": "Cerrado",
     "client_name": "pa",
     "user_name": "barra",
     "ticket_date": "2022-12-17 06:35:21",
     "total": "69.00",
     "nombre_mesa": "barra",
     "details": [
      {
       "id": 10,
       "units": 1,
       "unit_price": "69.00",
       "discounts": "0.00",
       "tax": "0.00",
       "subtotal": "69.00",
       "total": "69.00",
       "id_articulos": 3,
       "nombre_articulos": "pepsi",
       "articulos_img": "http:\/\/192.168.100.81:8000\/images",
       "status": "Recibido",
       "barTender_id": null,
       "waiter_id": 15,
       "ticket_id": 4,
       "deleted_at": null,
       "created_at": "2022-12-17T06:35:21.000000Z",
       "updated_at": "2022-12-17T06:36:09.000000Z"
      }
     ],
     "workshift": null,
     "payments": [
      {
       "id": 2,
       "type": "cash",
       "tip": "0.00",
       "total": "69.00",
       "diff": null,
       "nominas_paid": null,
       "vouchers": null,
       "nominas": null,
       "ticket_id": 4,
       "created_at": "2022-12-17T06:36:48.000000Z",
       "updated_at": "2022-12-17T06:36:48.000000Z"
      }
     ]
    }
   ],
   "non_closed_tickets": [
    {
     "id": 4,
     "status": "Entregado",
     "client_name": "pa",
     "user_name": "barra",
     "ticket_date": "2022-12-17 06:35:21",
     "total": "69.00",
     "nombre_mesa": "barra",
     "details": [
      {
       "id": 10,
       "units": 1,
       "unit_price": "69.00",
       "discounts": "0.00",
       "tax": "0.00",
       "subtotal": "69.00",
       "total": "69.00",
       "id_articulos": 3,
       "nombre_articulos": "pepsi",
       "articulos_img": "http:\/\/192.168.100.81:8000\/images",
       "status": "Recibido",
       "barTender_id": null,
       "waiter_id": 15,
       "ticket_id": 4,
       "deleted_at": null,
       "created_at": "2022-12-17T06:35:21.000000Z",
       "updated_at": "2022-12-17T06:36:09.000000Z"
      }
     ],
     "workshift": null,
     "payments": [
      {
       "id": 2,
       "type": "cash",
       "tip": "0.00",
       "total": "69.00",
       "diff": null,
       "nominas_paid": null,
       "vouchers": null,
       "nominas": null,
       "ticket_id": 4,
       "created_at": "2022-12-17T06:36:48.000000Z",
       "updated_at": "2022-12-17T06:36:48.000000Z"
      }
     ]
    }
   ],
   "canceled_tickets": [
    {
     "id": 4,
     "status": "Cancelado",
     "client_name": "pa",
     "user_name": "barra",
     "ticket_date": "2022-12-17 06:35:21",
     "total": "69.00",
     "nombre_mesa": "barra",
     "details": [
      {
       "id": 10,
       "units": 1,
       "unit_price": "69.00",
       "discounts": "0.00",
       "tax": "0.00",
       "subtotal": "69.00",
       "total": "69.00",
       "id_articulos": 3,
       "nombre_articulos": "pepsi",
       "articulos_img": "http:\/\/192.168.100.81:8000\/images",
       "status": "Recibido",
       "barTender_id": null,
       "waiter_id": 15,
       "ticket_id": 4,
       "deleted_at": null,
       "created_at": "2022-12-17T06:35:21.000000Z",
       "updated_at": "2022-12-17T06:36:09.000000Z"
      }
     ],
     "workshift": null,
     "payments": [
      {
       "id": 2,
       "type": "cash",
       "tip": "0.00",
       "total": "69.00",
       "diff": null,
       "nominas_paid": null,
       "vouchers": null,
       "nominas": null,
       "ticket_id": 4,
       "created_at": "2022-12-17T06:36:48.000000Z",
       "updated_at": "2022-12-17T06:36:48.000000Z"
      }
     ]
    }
   ]
  }
 ]
}`

**Comment by FaridCG343** [comment]
Ya quedó el método en el commit 54f30dba4aaf538b6de69905b735d07687c40d84
