### ISSUE TITLE
api:Crear una ruta/metodo especifica para pagar nominas

### ISSUE THREAD

**Issue by Lumexio** [Comet-Pocket-Machinery/Pocket-Bar#8]
- [x] Es necesario tener un metodo que reciba un array de objetos con los usuarios que obtendran un pago.
- [x] El monto total de las nominas debe restarse al monto todal actual de ventas confirmadas.
- [x] Crear la ruta que reciba el array de objetos api/nominas.
```json
[
  {
    "user_id":1,
    "name":"Jon",
    "payment":200.3
  },
]
```

**Comment by NathanRomero** [comment]
Ya quedo mi frank y esta es la estructura

```json
[
  "payroll":{
    "user_id":1,
    "name":"Jonh",
    "tip": 10,
    "payment":200.3
  },
]
````
ruta
```
/api/nominas/pay/
````
