### ISSUE TITLE
Websocket no responde bien cajero a mesero/barra   cierre de cuenta

### ISSUE THREAD

**Issue by Lumexio** [Comet-Pocket-Machinery/Pocket-Bar#9]
El metodo websoscket esta mal planteado y no esta actualizando el array venidero para renderizar en la lista de productos pendientes por preprar para un  barra

**Comment by Lumexio** [comment]
El problema radica en el momento en que exitosamente se cierra(paga) un ticket y no se actualiza la tabla con el array de tickets entregados del mesero o barra remitente. 
El comportamiento ideal es que al cerrar una cuenta, la cuenta cerrada debe a su vez actulizarce su estatus a "cerrado" con el Evento de ticketsCreated que refresque el array de la ruta tickets/list para que se renderice en la tabla con status cerrado a un barra o mesero. @NathanRomero @Mfireg

**Comment by NathanRomero** [comment]
Ya quedo parchado en la rama pwa

**Comment by Lumexio** [comment]
En revision mas profunda revisè el evento ticketCreated y este tuvo que ser reformulado.
La conclusiòn de el problema de los websockets no estan suficientemente especializados , puesto que al hacer un evento generico por tabla crea conflictos puesto que la talba tickets o el evento tickets es usado en diferentes metodos y por diferentes usuarios, entonces la correciòn inmedita radica en crea un  eventos para el cierre de los tickets y entre otras cosas que vaya ideando sobre la marcha. Por ahora la lista de tickets ya esta respondiendo bien, el problema solo era la utilizaciòn de wdindow.location en las llamadas al api en su reemplazo estoy utilizando un .env para que sea estatico y no varie al correr cada server manualmente y el cliente (front) e forma independiente como se hace respectivamente.

**Comment by Lumexio** [comment]
Cuando los articulos de un ticket son terminados por un Barra, el ticket en cuestion es cambiado a estatus entregado correctamente y llevado a la lista de tickets entregados en la pantalla del usuario emisor de esta cuenta.

**Comment by Lumexio** [comment]
El metodo indexpwa   tenia un problema al completar la preparacion de un ticket en todos sus articulos en el rol de un barra al no aparecer el ticket en el status de entregados, el problema fue solucionado  asignando correctamente el valor string de los objetos que se estaban validando para los ticketdetails. Sospecho que este codigo no fue probado antes de subirse.

**Comment by Lumexio** [comment]
Al cargar la pagina ol pwa en este caso, devolvia el status guardado en vuex pero no se sincronizaba el tab en el que deberia estar, tambien al terminar de un ticket por completo sus respectivos resquest para el barra cambian como deberian.
